language: android
android:
  components:
    - build-tools-28.0.3
    - android-28
    - android-21
    - add-on
    - extra
    - platform-tools
    - tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-28
    - sys-img-armeabi-v7a-android-21

env:
  global:
    # Add this
    - MALLOC_ARENA_MAX=2

sudo: required

licenses:
  - '.+'

before_install:
  - yes | sdkmanager "platforms;android-30"

deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: app/build/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    tags: true